# Generated by Django 3.2.5 on 2022-05-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('car_id_sales', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=200, null=True)),
                ('selling_date', models.DateField(blank=True, null=True)),
                ('selling_week', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('sell_price', models.CharField(blank=True, max_length=200, null=True)),
                ('transported_to_merchant', models.CharField(blank=True, max_length=200, null=True)),
                ('transport_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='table2',
            fields=[
                ('car_id_details', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('has_tuning', models.CharField(blank=True, max_length=200, null=True)),
                ('has_airbags', models.CharField(blank=True, max_length=200, null=True)),
                ('has_alarm_system', models.CharField(blank=True, max_length=200, null=True)),
                ('Models', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
