# Generated by Django 3.2.5 on 2022-05-24 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table1',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='table2',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table2',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='table1',
            name='merchant_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='table1',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='table1',
            name='sell_price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='table1',
            name='selling_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='table1',
            name='selling_week',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='table1',
            name='transport_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='table1',
            name='transported_to_merchant',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
