version: '3.8'

services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: DockerFile
    hostname: my-rabbit
    volumes:
      # - ./Users/chandru/opt/anaconda3/envs/rabbit
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 8081:8081
      - 15672:15672
    healthcheck:
      test:  rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 5s
      retries: 5
  pv_meter:
    build:
      context: ./pv_meter
      dockerfile: Dockerfile
    volumes:
      - ./pv_meter/log/:/src/log/
    environment:
      - broker_address=amqp://guest:guest@rabbitmq
      - broker_msg_queue=power
      - min_pv=0
      - max_pv=9000
      - publishing_interval_seconds=1
      - initial_delay_second_for_broker_startup=60
      - logfile=./log/producer.txt
    links:
      - "rabbitmq:rabbitmq"
    depends_on:
      - "rabbitmq"
  pv_simulation:
    build:
      context: ./pv_simulation
      dockerfile: Dockerfile
    volumes:
      - ./pv_simulation/log/:/src/log/
    environment:
      - broker_address=amqp://guest:guest@rabbitmq
      - broker_msg_queue=power
      - min_pv=0
      - max_pv=150
      - initial_delay_second_for_broker_startup=60
      - logfile=./log/consumer.txt
      - log_level=INFO
      - file_store=./log/pv.csv
    links:
      - "rabbitmq:rabbitmq"
    depends_on:
      - "rabbitmq"
